stages:
  - static_analysis
  - build
  - test

static_analysis:
  stage: static_analysis
  image: registry.gitlab.tugraz.at/asd25/repositories/team_03:latest
  script:
    - flutter doctor -v
    - flutter pub get
    - flutter analyze --no-pub

build:
  stage: build
  image: registry.gitlab.tugraz.at/asd25/repositories/team_03:latest
  script:
    - flutter build linux --release
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/linux/x64/release/bundle

test:
  stage: test
  image: registry.gitlab.tugraz.at/asd25/repositories/team_03:latest
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info -o coverage/html
  coverage: '/\s*lines\.*:\s*([\d\.]+%)/'
  artifacts:
    paths:
      - $CI_PROJECT_DIR/coverage/html
