stages:
  - build
  - test

build:
  stage: build
  image: registry.gitlab.tugraz.at/asd25/repositories/team_03:latest
  script:
    - flutter doctor -v
    - flutter pub get
    - flutter build linux --release
  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/linux/x64/release/bundle

test:
  stage: test
  image: registry.gitlab.tugraz.at/asd25/repositories/team_03:latest
  script:
    - flutter test
