// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTbFC3Du4I6P28Xj2juiDgExZuFeZM8K4',
    appId: '1:414183690281:web:39554b6e707308d8c04c38',
    messagingSenderId: '414183690281',
    projectId: 'budgetbuddy-asd',
    authDomain: 'budgetbuddy-asd.firebaseapp.com',
    storageBucket: 'budgetbuddy-asd.firebasestorage.app',
    measurementId: 'G-RMQ8T2WR9Y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvYPSkI5Q79hU84XP3lJztWtnbl7e4pA',
    appId: '1:414183690281:ios:1b7b7426ab57bb00c04c38',
    messagingSenderId: '414183690281',
    projectId: 'budgetbuddy-asd',
    storageBucket: 'budgetbuddy-asd.firebasestorage.app',
    iosBundleId: 'com.example.budgetbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTbFC3Du4I6P28Xj2juiDgExZuFeZM8K4',
    appId: '1:414183690281:web:d20c8a278e378a73c04c38',
    messagingSenderId: '414183690281',
    projectId: 'budgetbuddy-asd',
    authDomain: 'budgetbuddy-asd.firebaseapp.com',
    storageBucket: 'budgetbuddy-asd.firebasestorage.app',
    measurementId: 'G-95Q2NV8MPB',
  );

}